services:
  postgres:
    image: postgres:15
    container_name: huntly_db
    environment:
      POSTGRES_DB: huntly
      POSTGRES_USER: huntly_user
      POSTGRES_PASSWORD: huntly_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/test_schema.sql:/docker-entrypoint-initdb.d/02-test-schema.sql
    restart: unless-stopped

volumes:
  postgres_data:
